name: build

on: push

jobs:
  build:
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      BOT: bamboohr-slack-bot

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set output
      id: vars
      run: |
        if [ -z "${GITHUB_REF#refs/*/}" ]; then
          echo "release_version=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT
        else
          echo "release_version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        fi
        echo "bot_version=${BOT}_${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        echo "asset_name=${BOT}_${GITHUB_REF#refs/*/}_${GOOS}_${GOARCH}" >> $GITHUB_OUTPUT

    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.release_version }}
        BOT_VERSION: ${{ steps.vars.outputs.bot_version }}
        ASSET_NAME: ${{ steps.vars.outputs.asset_name }}
      run: |
        echo ${RELEASE_VERSION}
        echo ${BOT_VERSION}
        echo ${ASSET_NAME}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19

    - name: Get project dependencies
      run: go mod download

    - name: Build
      run: make build

    - name: Prepare a package
      run: |
        cp -v "bin/${BOT}" release
        cp -v config.yml-sample release

    - name: Build a debian package for linux
      if: matrix.goos == 'linux'
      run: |
        export PKG="release/debian/${BOT}"
        mkdir -p "${PKG}/opt/${BOT}/bin"
        cp -v "bin/${BOT}" "${PKG}/opt/${BOT}/bin"
        \cp -fv config.yml-sample "${PKG}/etc/${BOT}"
        sed -i "s/Version:.*/Version: ${{ steps.vars.outputs.release_version }}/" "${PKG}/DEBIAN/control"
        sed -i "s/Architecture:.*/Architecture: ${GOARCH}/" "${PKG}/DEBIAN/control"
        chmod -v u+x "${PKG}/opt/${BOT}/bin/${BOT}" "${PKG}/DEBIAN/postinst" "${PKG}/DEBIAN/postrm"
        mv -v "${PKG}" "${PKG}_${{ steps.vars.outputs.release_version }}-1"
        pushd release || exit 1
        dpkg-deb -v --build "debian/${BOT}_${{ steps.vars.outputs.release_version }}-1"
        popd || exit 1
        mv -v "${PKG}_${{ steps.vars.outputs.release_version }}-1.deb" release

    - name: Clean up
      run: |
        rm -frv release/debian
        mv release ${{ steps.vars.outputs.bot_version }}

    - name: Create a ZIP archive
      run: tar -cvzf ${{ steps.vars.outputs.asset_name }}.tar.gz ${{ steps.vars.outputs.bot_version }}

    - name: Upload binaries to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.vars.outputs.asset_name }}.tar.gz
        tag: ${{ github.ref }}
        overwrite: true




