name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set output
      id: vars
      run: echo "asset_name=bamboohr-slack-bot_${GITHUB_REF#refs/*/}_${GOOS}_${GOARCH}" >> $GITHUB_OUTPUT

    - name: Check output
      env:
        ASSET_NAME: ${{ steps.vars.outputs.asset_name }}
      run: |
        echo $ASSET_NAME

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19

    - name: Get project dependencies
      run: go mod download

    - name: Build
      run: make build

    - name: Prepare a package
      run: |
        mkdir -p ./build_assets
        cp bin/bamboohr-slack-bot ./build_assets
        cp -v config.yml-sample ./build_assets

    - name: Create a ZIP archive
      run: |
        pushd build_assets || exit 1
        zip -9vr ../${{ steps.vars.outputs.asset_name }}.zip .
        popd || exit 1

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.vars.outputs.asset_name }}.zip
        tag: ${{ github.ref }}
        overwrite: true




