name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set env
        run: echo "ASSET_NAME=bamboohr-slack-bot_${GITHUB_REF#refs/*/}_${GOOS}_${GOARCH}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Get project dependencies
        run: go mod download

      - name: Build
        run: make build

      - name: Prepare a package
        run: |
          mkdir -p ./build_assets
          cp bin/bamboohr-slack-bot ./build_assets
          cp -v config.yml-sample ./build_assets

      - name: Create ZIP archive
        run: |
          pushd build_assets || exit 1
          zip -9vr ../${ASSET_NAME}.zip .
          popd || exit 1
          FILE=./${ASSET_NAME}.zip
          DGST=$FILE.dgst
          openssl dgst -md5    $FILE | sed 's/([^)]*)//g' >>$DGST
          openssl dgst -sha1   $FILE | sed 's/([^)]*)//g' >>$DGST
          openssl dgst -sha256 $FILE | sed 's/([^)]*)//g' >>$DGST
          openssl dgst -sha512 $FILE | sed 's/([^)]*)//g' >>$DGST

      - name: Upload ZIP file to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${ASSET_NAME}.zip
          path: ${ASSET_NAME}.zip



